// frontend-react/src/pages/StatsHub.tsx
import { useState } from 'react'
import dayjs from 'dayjs'
import { ChartCard, DataTable, SectionHeader, DateRangePicker } from '@/components/shared/ui'
import EChart, { C } from '@/components/charts/EChart'
import { statsApi } from '@/api/statsApi'
import { dataApi }  from '@/api/dataApi'
import { useToastStore } from '@/store/appStore'

// rolling helpers
function rollingFn(arr: number[], w: number, fn: (s: number[]) => number) {
  return arr.map((_, i) => i < w - 1 ? null : fn(arr.slice(i - w + 1, i + 1)))
}
function sharpeSeries(r: number[], w = 252) {
  return rollingFn(r, w, sl => { const m = sl.reduce((a,b)=>a+b,0)/sl.length, s = Math.sqrt(sl.reduce((a,b)=>a+(b-m)**2,0)/sl.length); return s===0?0:+(m/s*Math.sqrt(252)).toFixed(4) })
}
function volSeries(r: number[], w = 252) {
  return rollingFn(r, w, sl => { const m = sl.reduce((a,b)=>a+b,0)/sl.length; return +(Math.sqrt(sl.reduce((a,b)=>a+(b-m)**2,0)/sl.length*252)*100).toFixed(4) })
}

const TABS = [
  { k:'regime',      l:'① Regime' },
  { k:'seasonality', l:'② Seasonality' },
  { k:'tailrisk',    l:'③ Tail Risk' },
  { k:'rolling',     l:'④ Rolling Stats' },
] as const
type Tab = typeof TABS[number]['k']

export default function StatsHub() {
  const toast = useToastStore()
  const [ticker,  setTicker]  = useState('SPY')
  const [start,   setStart]   = useState(dayjs().subtract(10,'year').format('YYYY-MM-DD'))
  const [end,     setEnd]     = useState(dayjs().format('YYYY-MM-DD'))
  const [tab,     setTab]     = useState<Tab>('regime')

  // Regime
  const [regLoading, setRL]  = useState(false)
  const [regimeOpt,  setRO]  = useState<any>(null)
  const [regStats,   setRS]  = useState<any[]>([])
  const [regText,    setRT]  = useState('')
  const REGIME_COLORS = ['#3b82f6','#ef4444','#f59e0b','#a78bfa']
  const REGIME_LABELS = ['Bull','Bear','Sideways','Volatile']
  const regimeCols = [
    { key:'label',      label:'Regime' },
    { key:'pct_time',   label:'% Time',  align:'right' as const, format:(v:unknown) => `${((v as number)*100).toFixed(1)}%` },
    { key:'avg_return', label:'Avg Ret', align:'right' as const, colorize:true, format:(v:unknown) => `${((v as number)*100).toFixed(2)}%` },
    { key:'volatility', label:'Vol',     align:'right' as const, format:(v:unknown) => `${((v as number)*100).toFixed(2)}%` },
  ]
  async function loadRegime() {
    setRL(true)
    try {
      const r = await statsApi.regime(ticker, 3, start, end)
      const d = r.data
      const dates   = d.regimes.map((r: any) => r.date)
      const regimes = d.regimes.map((r: any) => r.regime)
      const nS = new Set(regimes).size
      setRO({ tooltip:{ ...C.TOOLTIP }, legend:{ data:REGIME_LABELS.slice(0,nS), bottom:0, textStyle:{ color:'#94a3b8' } },
        grid:{ ...C.GRID, bottom:'18%' }, xAxis:{ ...C.XAXIS, data:dates }, yAxis:{ ...C.YAXIS, max:1, axisLabel:{ show:false } },
        dataZoom: C.DATAZONE,
        series: Array.from({length:nS},(_,si) => ({
          name:REGIME_LABELS[si]??`State ${si}`, type:'line', stack:'r',
          data:regimes.map((r:number) => r===si?1:0), symbol:'none',
          areaStyle:{ color:REGIME_COLORS[si]+'99' }, lineStyle:{ width:0 } }) ) })
      setRS(d.stats.map((s: any) => ({ ...s, label: REGIME_LABELS[s.regime]??`State ${s.regime}` })))
      const bull = d.stats.find((s:any) => s.regime===0), bear = d.stats.find((s:any) => s.regime===1)
      setRT(`${ticker} อยู่ใน Bull ${bull?((bull.pct_time as number)*100).toFixed(1):'?'}% และ Bear ${bear?((bear.pct_time as number)*100).toFixed(1):'?'}% ของช่วงเวลาที่เลือก`)
    } catch { toast.error('โหลด Regime ล้มเหลว') } finally { setRL(false) }
  }

  // Seasonality
  const [seaLoading, setSL] = useState(false)
  const [dowOpt,  setDOW]   = useState<any>(null)
  const [monOpt,  setMon]   = useState<any>(null)
  const [janEff,  setJan]   = useState<any>(null)
  const [monEff,  setMonE]  = useState<any>(null)
  function barOpt(labels: string[], values: number[]) {
    return { tooltip:{ ...C.TOOLTIP }, grid:{ ...C.GRID },
      xAxis:{ ...C.XAXIS, data:labels }, yAxis:{ ...C.YAXIS, axisLabel:{ ...C.YAXIS.axisLabel, formatter:(v:number) => `${(v*100).toFixed(2)}%` } },
      series:[{ type:'bar', data:values.map(v=>({ value:v, itemStyle:{ color:v>=0?'#22c55e':'#ef4444', borderRadius:[4,4,0,0] } })), barMaxWidth:40 }] }
  }
  async function loadSeasonality() {
    setSL(true)
    try {
      const r = await statsApi.seasonality(ticker, start, end)
      const d = r.data
      const DOW = ['Mon','Tue','Wed','Thu','Fri']
      const MON = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
      setDOW(barOpt(d.day_of_week.map((r:any) => DOW[+(r.day_num??r.label)]??r.label), d.day_of_week.map((r:any)=>r.mean_return)))
      setMon(barOpt(d.month.map((r:any) => MON[+(r.month_num??r.label)-1]??r.label), d.month.map((r:any)=>r.mean_return)))
      setJan(d.january_effect); setMonE(d.monday_effect)
    } catch { toast.error('โหลด Seasonality ล้มเหลว') } finally { setSL(false) }
  }

  // Tail Risk
  const [distLoading, setDL] = useState(false)
  const [tailOpt,  setTail]  = useState<any>(null)
  const [varRows,  setVarR]  = useState<any[]>([])
  const [bestFit,  setBF]    = useState<any>(null)
  const varCols = [
    { key:'method', label:'Method' },
    { key:'var95',  label:'VaR 95%', align:'right' as const, colorize:true, format:(v:unknown) => v!=null?`${((v as number)*100).toFixed(3)}%`:'—' },
    { key:'var99',  label:'VaR 99%', align:'right' as const, colorize:true, format:(v:unknown) => v!=null?`${((v as number)*100).toFixed(3)}%`:'—' },
  ]
  async function loadDistribution() {
    setDL(true)
    try {
      const r = await statsApi.distribution(ticker, start, end)
      const d = r.data, tr = d.tail_risk
      setVarR([
        { method:'Historical',    var95:tr['var_hist_95']??tr['var_95'], var99:tr['var_hist_99']??tr['var_99'] },
        { method:'Parametric',    var95:tr['var_param_95']??tr['var_95'], var99:tr['var_param_99']??tr['var_99'] },
        { method:'Cornish-Fisher',var95:tr['var_cf_95']??tr['var_95'],   var99:tr['var_cf_99']??tr['var_99'] },
      ])
      setBF(tr['best_fit']??d.best_fit)
      const pts = ['VaR 90%','VaR 95%','VaR 99%','CVaR 90%','CVaR 95%','CVaR 99%'].map((l,i) => {
        const keys = [['var_hist_90'],['var_hist_95'],['var_hist_99'],['cvar_hist_90'],['cvar_hist_95'],['cvar_hist_99']]
        return { label:l, val:tr[keys[i][0]] }
      }).filter(p => p.val!=null)
      setTail({ tooltip:{ ...C.TOOLTIP }, grid:{ ...C.GRID }, xAxis:{ ...C.XAXIS, data:pts.map(p=>p.label) },
        yAxis:{ ...C.YAXIS, axisLabel:{ ...C.YAXIS.axisLabel, formatter:(v:number)=>`${(v*100).toFixed(2)}%` } },
        series:[{ type:'bar', data:pts.map(p=>+(p.val as number).toFixed(6)), barMaxWidth:40, itemStyle:{ color:'#ef4444', borderRadius:[4,4,0,0] } }] })
    } catch { toast.error('โหลด Tail Risk ล้มเหลว') } finally { setDL(false) }
  }

  // Rolling
  const [rollLoading, setRollL] = useState(false)
  const [rollW, setRollW]       = useState(252)
  const [bmTicker, setBm]       = useState('SPY')
  const [sharpeOpt, setSharpeO] = useState<any>(null)
  const [volOpt,    setVolO]    = useState<any>(null)
  const [betaOpt,   setBetaO]   = useState<any>(null)
  function rollChart(dates: string[], vals: (number|null)[], name: string, color: string) {
    return { tooltip:{ ...C.TOOLTIP }, grid:{ ...C.GRID, bottom:'14%' }, xAxis:{ ...C.XAXIS, data:dates }, yAxis:{ ...C.YAXIS },
      dataZoom: C.DATAZONE,
      series:[{ name, type:'line', data:vals, symbol:'none', lineStyle:{ color, width:1.5 }, areaStyle:{ color:color+'18' },
        markLine:{ silent:true, lineStyle:{ color:'#334155', type:'dashed' }, data:[{ yAxis:0 }] } }] }
  }
  async function loadRolling() {
    setRollL(true)
    try {
      const [pRes, bRes] = await Promise.all([dataApi.prices(ticker, start, end), dataApi.prices(bmTicker, start, end)])
      const bars  = pRes.data.data, bBars = bRes.data.data
      const dates = bars.slice(1).map((b: any) => b.date)
      const rets  = bars.slice(1).map((b: any, i: number) => (b.close - bars[i].close) / bars[i].close)
      const bRets = bBars.slice(1).map((b: any, i: number) => (b.close - bBars[i].close) / bBars[i].close)
      const sharpe = sharpeSeries(rets, rollW)
      const vol    = volSeries(rets, rollW)
      const beta   = rets.map((_,i) => {
        if (i < rollW-1) return null
        const rs=rets.slice(i-rollW+1,i+1), bs=bRets.slice(i-rollW+1,i+1)
        const mr=rs.reduce((a,b)=>a+b,0)/rs.length, mb=bs.reduce((a,b)=>a+b,0)/bs.length
        const cov=rs.reduce((a,r,j)=>a+(r-mr)*(bs[j]-mb),0)/rs.length
        const vb=bs.reduce((a,b)=>a+(b-mb)**2,0)/bs.length
        return vb===0?null:+(cov/vb).toFixed(4)
      })
      setSharpeO(rollChart(dates, sharpe, 'Sharpe', '#3b82f6'))
      setVolO(rollChart(dates, vol, 'Vol %', '#f59e0b'))
      setBetaO(rollChart(dates, beta, 'Beta', '#a78bfa'))
    } catch { toast.error('โหลด Rolling Stats ล้มเหลว') } finally { setRollL(false) }
  }

  function runTab() {
    if (tab==='regime')      loadRegime()
    else if (tab==='seasonality') loadSeasonality()
    else if (tab==='tailrisk')    loadDistribution()
    else loadRolling()
  }

  return (
    <div className="space-y-5 animate-fade-in">
      <SectionHeader title="Statistical Analysis Hub" description="Regime · Seasonality · Tail Risk · Rolling Stats">
        <div className="flex items-center gap-2 flex-wrap">
          <input value={ticker} onChange={e => setTicker(e.target.value.toUpperCase())} placeholder="Ticker" className="input-base w-24 text-sm py-1.5"/>
          <DateRangePicker start={start} end={end} onChange={(s,e) => { setStart(s); setEnd(e) }}/>
        </div>
      </SectionHeader>

      {/* Tab bar */}
      <div className="flex border-b border-surface-700/50 gap-1">
        {TABS.map(t => (
          <button key={t.k} onClick={() => setTab(t.k)} className={`tab-item ${tab===t.k?'tab-active':''}`}>{t.l}</button>
        ))}
      </div>

      {/* Run button */}
      <div className="flex justify-end">
        <button onClick={runTab} className="btn-primary text-sm">Analyse {ticker}</button>
      </div>

      {/* Regime Tab */}
      {tab==='regime' && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <div className="lg:col-span-2">
              <ChartCard title="HMM Regime Chart" subtitle="Last 252 trading days" loading={regLoading} onRefresh={loadRegime}>
                {regimeOpt && <EChart option={regimeOpt} style={{ height:260 }}/>}
              </ChartCard>
            </div>
            <ChartCard title="Regime Statistics" loading={regLoading}>
              {regStats.length > 0 && <DataTable columns={regimeCols} rows={regStats}/>}
            </ChartCard>
          </div>
          {regText && <div className="glass p-4 border-l-2 border-primary-500"><p className="text-sm text-surface-300 leading-relaxed">{regText}</p></div>}
        </div>
      )}

      {/* Seasonality Tab */}
      {tab==='seasonality' && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <ChartCard title="Day-of-Week Effect" loading={seaLoading} onRefresh={loadSeasonality}>
              {dowOpt && <EChart option={dowOpt} style={{ height:240 }}/>}
            </ChartCard>
            <ChartCard title="Month-of-Year Effect" loading={seaLoading} onRefresh={loadSeasonality}>
              {monOpt && <EChart option={monOpt} style={{ height:240 }}/>}
            </ChartCard>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {[{ title:'January Effect', eff:janEff, posKey:'avg_jan', negKey:'avg_other', posLabel:'Avg Jan', negLabel:'Avg Other' },
              { title:'Monday Effect',  eff:monEff, posKey:'avg_mon', negKey:'avg_other', posLabel:'Avg Mon', negLabel:'Avg Other' }].map(({ title, eff, posKey, negKey, posLabel, negLabel }) => (
              <div key={title} className="glass p-4 space-y-2">
                <h4 className="text-sm font-semibold text-surface-200">{title}</h4>
                {eff && <>
                  <span className={`badge ${eff.detected?'badge-bull':'badge-bear'}`}>{eff.detected?'Detected':'Not Detected'}</span>
                  <span className="text-xs text-surface-400 ml-2">p = {eff.p_value?.toFixed(4)}</span>
                  <p className="text-xs text-surface-400">{posLabel}: <span className="text-surface-200 font-medium">{(eff[posKey]*100).toFixed(3)}%</span> vs {negLabel}: <span className="text-surface-200 font-medium">{(eff[negKey]*100).toFixed(3)}%</span></p>
                </>}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tail Risk Tab */}
      {tab==='tailrisk' && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <div className="lg:col-span-2">
              <ChartCard title="VaR Comparison" loading={distLoading} onRefresh={loadDistribution}>
                {tailOpt && <EChart option={tailOpt} style={{ height:280 }}/>}
              </ChartCard>
            </div>
            <div className="space-y-3">
              <ChartCard title="VaR Table" loading={distLoading}>
                {varRows.length > 0 && <DataTable columns={varCols} rows={varRows}/>}
              </ChartCard>
              {bestFit && (
                <div className="glass p-4 space-y-1.5">
                  <h4 className="text-xs font-semibold text-surface-400 uppercase tracking-wider">Best Fit</h4>
                  <p className="text-sm font-bold text-primary-400">{bestFit.name}</p>
                  <p className="text-xs text-surface-400">KS p-value: <span className="text-surface-200">{bestFit.ks_pvalue?.toFixed(4)}</span></p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Rolling Tab */}
      {tab==='rolling' && (
        <div className="space-y-4">
          <div className="flex items-center gap-3 flex-wrap">
            <label className="text-xs text-surface-400">Window</label>
            <select value={rollW} onChange={e => setRollW(+e.target.value)} className="input-base text-sm py-1.5 w-36">
              {[{v:63,l:'63 (Quarter)'},{v:126,l:'126 (Half-yr)'},{v:252,l:'252 (1 Year)'},{v:504,l:'504 (2 Years)'}].map(o => <option key={o.v} value={o.v}>{o.l}</option>)}
            </select>
            <label className="text-xs text-surface-400">Benchmark</label>
            <input value={bmTicker} onChange={e => setBm(e.target.value.toUpperCase())} className="input-base w-20 text-sm py-1.5"/>
            <button onClick={loadRolling} disabled={rollLoading} className="btn-primary text-sm">Compute</button>
          </div>
          {[{ opt:sharpeOpt, title:'Rolling Sharpe' },{ opt:volOpt, title:'Rolling Volatility %' },{ opt:betaOpt, title:`Rolling Beta vs ${bmTicker}` }].map(({ opt, title }) => (
            <ChartCard key={title} title={title} loading={rollLoading}>
              {opt && <EChart option={opt} style={{ height:200 }}/>}
            </ChartCard>
          ))}
        </div>
      )}
    </div>
  )
}

// frontend/src/views/StatsHub.vue
<template>
  <div class="space-y-5 animate-fade-in">
    <SectionHeader title="Statistical Analysis Hub" description="Regime detection · Seasonality · Tail risk · Rolling statistics">
      <div class="flex items-center gap-2">
        <div class="w-36">
          <TickerSearch :model-value="[ticker]" @update:model-value="v => ticker = v[0] ?? 'SPY'" :multi="false" />
        </div>
        <DateRangePicker v-model="dateRange" />
      </div>
    </SectionHeader>

    <!-- Tab bar -->
    <div class="flex border-b border-surface-700/50 gap-1">
      <button v-for="tab in tabs" :key="tab.key"
        @click="activeTab = tab.key"
        class="tab-item" :class="{ active: activeTab === tab.key }">
        {{ tab.label }}
      </button>
    </div>

    <!-- ── Tab 1: Regime Detection ───────────────────────────────────────── -->
    <div v-if="activeTab === 'regime'" class="space-y-4">
      <div class="flex justify-end">
        <button @click="loadRegime" :disabled="regimeLoading" class="btn-primary text-sm">
          <svg v-if="regimeLoading" class="w-4 h-4 animate-spin inline mr-1" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>
          Analyse Regimes
        </button>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div class="lg:col-span-2">
          <ChartCard title="HMM Regime Chart" subtitle="Last 252 trading days" :loading="regimeLoading" :height="260" @refresh="loadRegime">
            <VChart v-if="regimeOption" :option="regimeOption" autoresize style="height:260px" />
          </ChartCard>
        </div>
        <ChartCard title="Regime Statistics" :loading="regimeLoading" :height="260">
          <DataTable v-if="regimeStats.length" :columns="regimeCols" :rows="regimeStats" />
        </ChartCard>
      </div>

      <!-- Interpretation -->
      <div v-if="regimeInterpretation" class="glass p-4 border-l-2 border-primary-500">
        <p class="text-sm text-surface-300 leading-relaxed">{{ regimeInterpretation }}</p>
      </div>
    </div>

    <!-- ── Tab 2: Seasonality ─────────────────────────────────────────────── -->
    <div v-if="activeTab === 'seasonality'" class="space-y-4">
      <div class="flex justify-end">
        <button @click="loadSeasonality" :disabled="seasonLoading" class="btn-primary text-sm">Analyse Seasonality</button>
      </div>
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <ChartCard title="Day-of-Week Effect" subtitle="Average return per weekday" :loading="seasonLoading" @refresh="loadSeasonality">
          <VChart v-if="dowOption" :option="dowOption" autoresize style="height:240px" />
        </ChartCard>
        <ChartCard title="Month-of-Year Effect" subtitle="Average return per calendar month" :loading="seasonLoading" @refresh="loadSeasonality">
          <VChart v-if="monthOption" :option="monthOption" autoresize style="height:240px" />
        </ChartCard>
      </div>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div class="glass p-4 space-y-2">
          <h4 class="text-sm font-semibold text-surface-200">January Effect</h4>
          <template v-if="januaryEffect">
            <div class="flex items-center gap-2">
              <span class="badge" :class="januaryEffect.detected ? 'badge-bull' : 'badge-bear'">
                {{ januaryEffect.detected ? 'Detected' : 'Not Detected' }}
              </span>
              <span class="text-xs text-surface-400">p = {{ januaryEffect.p_value?.toFixed(4) }}</span>
            </div>
            <p class="text-xs text-surface-400">Avg Jan: <span class="text-surface-200 font-medium">{{ (januaryEffect.avg_jan * 100).toFixed(3) }}%</span> vs Other: <span class="text-surface-200 font-medium">{{ (januaryEffect.avg_other * 100).toFixed(3) }}%</span></p>
          </template>
        </div>
        <div class="glass p-4 space-y-2">
          <h4 class="text-sm font-semibold text-surface-200">Monday Effect</h4>
          <template v-if="mondayEffect">
            <div class="flex items-center gap-2">
              <span class="badge" :class="mondayEffect.detected ? 'badge-bull' : 'badge-bear'">
                {{ mondayEffect.detected ? 'Detected' : 'Not Detected' }}
              </span>
              <span class="text-xs text-surface-400">p = {{ mondayEffect.p_value?.toFixed(4) }}</span>
            </div>
            <p class="text-xs text-surface-400">Avg Mon: <span class="text-surface-200 font-medium">{{ (mondayEffect.avg_mon * 100).toFixed(3) }}%</span> vs Other: <span class="text-surface-200 font-medium">{{ (mondayEffect.avg_other * 100).toFixed(3) }}%</span></p>
          </template>
        </div>
      </div>
    </div>

    <!-- ── Tab 3: Tail Risk ───────────────────────────────────────────────── -->
    <div v-if="activeTab === 'tailrisk'" class="space-y-4">
      <div class="flex justify-end">
        <button @click="loadDistribution" :disabled="distLoading" class="btn-primary text-sm">Analyse Tail Risk</button>
      </div>
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div class="lg:col-span-2">
          <ChartCard title="Tail Risk Curve" subtitle="Empirical loss quantiles" :loading="distLoading" @refresh="loadDistribution">
            <VChart v-if="tailOption" :option="tailOption" autoresize style="height:280px" />
          </ChartCard>
        </div>
        <div class="space-y-3">
          <ChartCard title="VaR Comparison" :loading="distLoading" :height="150">
            <DataTable v-if="varRows.length" :columns="varCols" :rows="varRows" />
          </ChartCard>
          <div v-if="bestFit" class="glass p-4 space-y-1.5">
            <h4 class="text-xs font-semibold text-surface-400 uppercase tracking-wider">Best Fit Distribution</h4>
            <p class="text-sm font-bold text-primary-400">{{ bestFit.name }}</p>
            <p class="text-xs text-surface-400">KS p-value: <span class="text-surface-200">{{ bestFit.ks_pvalue?.toFixed(4) }}</span></p>
            <p class="text-xs text-surface-400">KS stat: <span class="text-surface-200">{{ bestFit.ks_stat?.toFixed(4) }}</span></p>
          </div>
        </div>
      </div>
    </div>

    <!-- ── Tab 4: Rolling Stats ───────────────────────────────────────────── -->
    <div v-if="activeTab === 'rolling'" class="space-y-4">
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
          <label class="text-xs text-surface-400">Window (days)</label>
          <select v-model="rollingWindow" class="bg-surface-800 border border-surface-700 text-sm text-surface-200 rounded-md px-2 py-1 outline-none focus:border-primary-500">
            <option :value="63">63 (Quarter)</option>
            <option :value="126">126 (Half-year)</option>
            <option :value="252">252 (1 Year)</option>
            <option :value="504">504 (2 Years)</option>
          </select>
          <label class="text-xs text-surface-400">Benchmark</label>
          <input v-model="benchmark" class="w-20 bg-surface-800 border border-surface-700 text-sm text-surface-200 rounded-md px-2 py-1 outline-none focus:border-primary-500" />
        </div>
        <button @click="loadRolling" :disabled="rollingLoading" class="btn-primary text-sm">Compute Rolling</button>
      </div>

      <ChartCard title="Rolling Sharpe Ratio" :subtitle="`${rollingWindow}-day rolling window`" :loading="rollingLoading" @refresh="loadRolling">
        <VChart v-if="rollingSharpeOption" :option="rollingSharpeOption" autoresize style="height:200px" />
      </ChartCard>
      <ChartCard title="Rolling Annualised Volatility (%)" :subtitle="`${rollingWindow}-day rolling window`" :loading="rollingLoading">
        <VChart v-if="rollingVolOption" :option="rollingVolOption" autoresize style="height:200px" />
      </ChartCard>
      <ChartCard title="Rolling Beta vs Benchmark" :subtitle="`${rollingWindow}-day window vs ${benchmark}`" :loading="rollingLoading">
        <VChart v-if="rollingBetaOption" :option="rollingBetaOption" autoresize style="height:200px" />
      </ChartCard>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import dayjs from 'dayjs'
import SectionHeader   from '@/components/shared/SectionHeader.vue'
import ChartCard       from '@/components/shared/ChartCard.vue'
import DataTable       from '@/components/shared/DataTable.vue'
import TickerSearch    from '@/components/shared/TickerSearch.vue'
import DateRangePicker from '@/components/shared/DateRangePicker.vue'
import { statsApi } from '@/api/statsApi'
import { dataApi  } from '@/api/dataApi'
import type { DateRange } from '@/types'
import {
  BASE_TOOLTIP, BASE_GRID, BASE_XAXIS, BASE_YAXIS, BASE_DATAZONE,
  CHART_COLORS, sharpeSeries, volSeries, priceToReturns,
} from '@/components/charts/chartTheme'

const ticker    = ref('SPY')
const dateRange = ref<DateRange>({
  start: dayjs().subtract(10, 'year').format('YYYY-MM-DD'),
  end:   dayjs().format('YYYY-MM-DD'),
})
const activeTab = ref<'regime' | 'seasonality' | 'tailrisk' | 'rolling'>('regime')
const tabs = [
  { key: 'regime'      as const, label: '① Regime Detection' },
  { key: 'seasonality' as const, label: '② Seasonality' },
  { key: 'tailrisk'    as const, label: '③ Tail Risk' },
  { key: 'rolling'     as const, label: '④ Rolling Stats' },
]

// ── Regime ────────────────────────────────────────────────────────────────────
const regimeLoading      = ref(false)
const regimeOption       = ref<Record<string, unknown> | null>(null)
const regimeStats        = ref<Record<string, unknown>[]>([])
const regimeInterpretation = ref('')

const REGIME_COLORS = ['#3b82f6', '#ef4444', '#f59e0b', '#a78bfa']
const REGIME_LABELS = ['Bull', 'Bear', 'Sideways', 'Volatile']

const regimeCols = [
  { key: 'label',      label: 'Regime' },
  // pct_time is fraction 0-1 from backend — format as percentage
  { key: 'pct_time',   label: '% Time',   align: 'right' as const, format: (v: unknown) => `${((v as number) * 100).toFixed(1)}%` },
  // avg_return is annualised — already in decimal form
  { key: 'avg_return', label: 'Avg Ret',  align: 'right' as const, colorize: true, format: (v: unknown) => `${((v as number) * 100).toFixed(2)}%` },
  { key: 'volatility', label: 'Vol',      align: 'right' as const, format: (v: unknown) => `${((v as number) * 100).toFixed(2)}%` },
]

async function loadRegime() {
  regimeLoading.value = true
  try {
    const res = await statsApi.regime(ticker.value, 3, dateRange.value.start, dateRange.value.end)
    const d = res.data
    const dates   = d.regimes.map((r) => r.date)
    const regimes = d.regimes.map((r) => r.regime)

    // Build stacked area: one series per regime state
    const nStates = new Set(regimes).size
    const seriesData = Array.from({ length: nStates }, (_, si) =>
      regimes.map((r) => (r === si ? 1 : 0))
    )

    regimeOption.value = {
      tooltip:  { ...BASE_TOOLTIP, trigger: 'axis' },
      legend:   { data: REGIME_LABELS.slice(0, nStates), bottom: 0, textStyle: { color: '#94a3b8' } },
      grid:     { ...BASE_GRID, bottom: '18%' },
      xAxis:    { ...BASE_XAXIS, data: dates },
      yAxis:    { ...BASE_YAXIS, max: 1, axisLabel: { show: false } },
      dataZoom: BASE_DATAZONE,
      series:   seriesData.map((data, si) => ({
        name: REGIME_LABELS[si] ?? `State ${si}`,
        type: 'line', data, stack: 'regime',
        symbol: 'none', smooth: false,
        areaStyle: { color: REGIME_COLORS[si] + '99' },
        lineStyle: { width: 0 },
      })),
    }

    // Stats table — backend already renamed pct_days→pct_time and mean_return→avg_return
    regimeStats.value = d.stats.map((s) => ({
      ...s,
      label: REGIME_LABELS[s.regime as number] ?? `State ${s.regime}`,
    }))

    // Interpretation text — pct_time is now 0-1 fraction
    if (d.stats.length) {
      const bull = d.stats.find((s) => s.regime === 0)
      const bear = d.stats.find((s) => s.regime === 1)
      const pBull = bull ? ((bull.pct_time as number) * 100).toFixed(1) : '?'
      const pBear = bear ? ((bear.pct_time as number) * 100).toFixed(1) : '?'
      regimeInterpretation.value = `${ticker.value} was in Bull regime ${pBull}% and Bear regime ${pBear}% of the time over the selected period.${bull && (bull.avg_return as number) > 0 ? ' Positive average returns in bull state confirm upward trend bias.' : ''}`
    }
  } finally {
    regimeLoading.value = false
  }
}

// ── Seasonality ───────────────────────────────────────────────────────────────
const seasonLoading = ref(false)
const dowOption     = ref<Record<string, unknown> | null>(null)
const monthOption   = ref<Record<string, unknown> | null>(null)
const januaryEffect = ref<{ detected: boolean; p_value: number; avg_jan: number; avg_other: number } | null>(null)
const mondayEffect  = ref<{ detected: boolean; p_value: number; avg_mon: number; avg_other: number } | null>(null)

function makeEffectBar(labels: string[], values: number[], stds: number[], color = '#3b82f6') {
  return {
    tooltip:  { ...BASE_TOOLTIP },
    grid:     { ...BASE_GRID },
    xAxis:    { ...BASE_XAXIS, data: labels },
    yAxis:    { ...BASE_YAXIS, axisLabel: { ...BASE_YAXIS.axisLabel, formatter: (v: number) => `${(v*100).toFixed(2)}%` } },
    series: [{
      type: 'bar', data: values.map((v, i) => ({
        value: v,
        itemStyle: { color: v >= 0 ? '#22c55e' : '#ef4444', borderRadius: [4, 4, 0, 0] },
      })), barMaxWidth: 40,
    }],
  }
}

async function loadSeasonality() {
  seasonLoading.value = true
  try {
    const res = await statsApi.seasonality(ticker.value, dateRange.value.start, dateRange.value.end)
    const d = res.data

    const DOW_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
    dowOption.value = makeEffectBar(
      d.day_of_week.map((r) => {
        const n = r.day_num ?? r.label
        return DOW_LABELS[Number(n)] ?? String(n)
      }),
      d.day_of_week.map((r) => r.mean_return as number),
      d.day_of_week.map((r) => r.std as number),
    )

    const MONTH_LABELS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
    monthOption.value = makeEffectBar(
      d.month.map((r) => {
        const n = r.month_num ?? r.label
        return MONTH_LABELS[Number(n) - 1] ?? String(n)
      }),
      d.month.map((r) => r.mean_return as number),
      d.month.map((r) => r.std as number),
    )

    januaryEffect.value = d.january_effect as typeof januaryEffect.value
    mondayEffect.value  = d.monday_effect as typeof mondayEffect.value
  } finally {
    seasonLoading.value = false
  }
}

// ── Tail Risk ─────────────────────────────────────────────────────────────────
const distLoading = ref(false)
const tailOption  = ref<Record<string, unknown> | null>(null)
const varRows     = ref<Record<string, unknown>[]>([])
const bestFit     = ref<{ name: string; ks_pvalue: number; ks_stat: number } | null>(null)

const varCols = [
  { key: 'method', label: 'Method' },
  { key: 'var95',  label: 'VaR 95%', align: 'right' as const, colorize: true, format: (v: unknown) => `${((v as number)*100).toFixed(3)}%` },
  { key: 'var99',  label: 'VaR 99%', align: 'right' as const, colorize: true, format: (v: unknown) => `${((v as number)*100).toFixed(3)}%` },
]

async function loadDistribution() {
  distLoading.value = true
  try {
    const res = await statsApi.distribution(ticker.value, dateRange.value.start, dateRange.value.end)
    const d = res.data
    const tr = d.tail_risk

    varRows.value = [
      {
        method: 'Historical',
        var95: tr['var_hist_95']  ?? tr['var_95_hist']  ?? tr['var_95'],
        var99: tr['var_hist_99']  ?? tr['var_99_hist']  ?? tr['var_99'],
      },
      {
        method: 'Parametric',
        var95: tr['var_param_95'] ?? tr['var_95_param'] ?? tr['var_95'],
        var99: tr['var_param_99'] ?? tr['var_99_param'] ?? tr['var_99'],
      },
      {
        method: 'Cornish-Fisher',
        var95: tr['var_cf_95']    ?? tr['var_95_cf']    ?? tr['var_95'],
        var99: tr['var_cf_99']    ?? tr['var_99_cf']    ?? tr['var_99'],
      },
    ]

    // best_fit is nested inside tail_risk dict (from DistributionAnalysis.tail_risk_report)
    const bf = tr['best_fit'] ?? d.best_fit
    bestFit.value = bf as typeof bestFit.value

    // Empirical tail quantile chart — keys are var_hist_90, var_hist_95, var_hist_99
    const quantiles = [90, 95, 99]
    const qValues = quantiles.map((q) =>
      tr[`var_hist_${q}`] ?? tr[`var_${q}`] ?? null
    )
    // Add CVaR points too for a richer curve
    const allPoints = [
      { label: 'VaR 90%', val: tr['var_hist_90']  ?? tr['var_hist_90']  ?? null },
      { label: 'VaR 95%', val: tr['var_hist_95']  ?? null },
      { label: 'VaR 99%', val: tr['var_hist_99']  ?? null },
      { label: 'CVaR 90%',val: tr['cvar_hist_90'] ?? null },
      { label: 'CVaR 95%',val: tr['cvar_hist_95'] ?? null },
      { label: 'CVaR 99%',val: tr['cvar_hist_99'] ?? null },
    ].filter((p) => p.val !== null)
    tailOption.value = {
      tooltip:  { ...BASE_TOOLTIP },
      grid:     { ...BASE_GRID },
      xAxis:    { ...BASE_XAXIS, data: allPoints.map((p) => p.label) },
      yAxis:    { ...BASE_YAXIS, axisLabel: { ...BASE_YAXIS.axisLabel, formatter: (v: number) => `${(v * 100).toFixed(2)}%` } },
      series: [{
        name: 'Loss', type: 'bar', barMaxWidth: 40,
        data: allPoints.map((p) => +(p.val as number).toFixed(6)),
        itemStyle: { color: '#ef4444', borderRadius: [4, 4, 0, 0] },
        label: { show: true, position: 'top', color: '#f1f5f9', fontSize: 10,
          formatter: (p: { value: number }) => `${(p.value * 100).toFixed(2)}%` },
      }],
    }
  } finally {
    distLoading.value = false
  }
}

// ── Rolling Stats ─────────────────────────────────────────────────────────────
const rollingLoading      = ref(false)
const rollingWindow       = ref(252)
const benchmark           = ref('SPY')
const rollingSharpeOption = ref<Record<string, unknown> | null>(null)
const rollingVolOption    = ref<Record<string, unknown> | null>(null)
const rollingBetaOption   = ref<Record<string, unknown> | null>(null)

function makeRollingChart(dates: string[], values: (number | null)[], name: string, color: string, yFmt?: (v: number) => string) {
  return {
    tooltip:  { ...BASE_TOOLTIP },
    grid:     { ...BASE_GRID, bottom: '14%' },
    xAxis:    { ...BASE_XAXIS, data: dates },
    yAxis:    { ...BASE_YAXIS, ...(yFmt ? { axisLabel: { ...BASE_YAXIS.axisLabel, formatter: yFmt } } : {}) },
    dataZoom: BASE_DATAZONE,
    series: [{
      name, type: 'line', data: values,
      symbol: 'none', smooth: false,
      lineStyle: { color, width: 1.5 },
      areaStyle: { color: color + '18' },
      markLine: {
        silent: true,
        lineStyle: { color: '#334155', type: 'dashed' },
        data: [{ yAxis: 0 }],
      },
    }],
  }
}

async function loadRolling() {
  rollingLoading.value = true
  try {
    const [prRes, bmRes] = await Promise.all([
      dataApi.prices(ticker.value,   dateRange.value.start, dateRange.value.end),
      dataApi.prices(benchmark.value, dateRange.value.start, dateRange.value.end),
    ])
    const bars  = prRes.data.data
    const bBars = bmRes.data.data

    const dates   = bars.slice(1).map((b) => b.date)
    const rets    = priceToReturns(bars.map((b) => b.close))
    const bmRets  = priceToReturns(bBars.map((b) => b.close))

    const sharpeArr = sharpeSeries(rets, rollingWindow.value)
    const volArr    = volSeries(rets, rollingWindow.value)

    // Beta = cov(r, bm) / var(bm)
    const betaArr = rets.map((_, i) => {
      if (i < rollingWindow.value - 1) return null
      const rSlice  = rets.slice(i - rollingWindow.value + 1, i + 1)
      const bmSlice = bmRets.slice(i - rollingWindow.value + 1, i + 1)
      if (bmSlice.length !== rSlice.length) return null
      const mR  = rSlice.reduce((a, b) => a + b, 0)  / rSlice.length
      const mBm = bmSlice.reduce((a, b) => a + b, 0) / bmSlice.length
      const cov = rSlice.reduce((a, r, j) => a + (r - mR) * (bmSlice[j] - mBm), 0) / rSlice.length
      const varBm = bmSlice.reduce((a, b) => a + (b - mBm) ** 2, 0) / bmSlice.length
      return varBm === 0 ? null : +(cov / varBm).toFixed(4)
    })

    rollingSharpeOption.value = makeRollingChart(dates, sharpeArr, 'Sharpe', '#3b82f6', (v) => v.toFixed(2))
    rollingVolOption.value    = makeRollingChart(dates, volArr,    'Vol %',  '#f59e0b', (v) => `${v.toFixed(1)}%`)
    rollingBetaOption.value   = makeRollingChart(dates, betaArr,   'Beta',   '#a78bfa', (v) => v.toFixed(2))
  } finally {
    rollingLoading.value = false
  }
}

watch([ticker, dateRange], () => {
  if (activeTab.value === 'regime')      loadRegime()
  else if (activeTab.value === 'seasonality') loadSeasonality()
  else if (activeTab.value === 'tailrisk')    loadDistribution()
  else                                        loadRolling()
}, { deep: true })
</script>
